```{r}
source('https://raw.githubusercontent.com/GabrielGabes/Codigos-uteis/main/R%20program/executar_sempre.R')
```


```{r}
library(readxl)
library(dplyr)

# Lista de arquivos
arquivos <- c(
  'Relatorio - Dor - Janeiro - Helena.xlsx',
  'Relatorio - Dor - Fevereiro - Helena.xlsx',
  'Relatorio - Dor - Março - Helena.xlsx',
  'Relatorio - Dor - Abril - Helena.xlsx',
  'Relatorio - Dor - Maio - Helena.xlsx',
  'Relatorio - Dor - Junho - Helena.xlsx',
  'Relatorio - Dor - Julho - Helena.xlsx'
)

# Caminho da pasta onde os arquivos estão armazenados
pasta <- "C:/Users/gabri/OneDrive/Documentos/Freelances/Acompanhamento dor/"

# Função para extrair o mês do nome do arquivo
extrair_mes <- function(nome_arquivo) {
  sub(".*Dor - (.*) - Helena.xlsx", "\\1", nome_arquivo)
}

# Carregando e concatenando os arquivos com a coluna de mês
df_final <- lapply(arquivos, function(arquivo) {
  # Extrair o mês
  mes <- extrair_mes(arquivo)
  
  # Ler o arquivo Excel
  df <- read_excel(paste0(pasta, arquivo))
  
  # Adicionar a coluna do mês
  df <- mutate(df, Mes = mes)
  
  return(df)
}) %>% bind_rows()

# Exibindo o DataFrame final
df = df_final
df

```
```{r}
# Função para normalizar os nomes das colunas
library(stringr)
normalize_column_names <- function(df) {
  # Remover acentuação
  colnames(df) <- iconv(colnames(df), from = "UTF-8", to = "ASCII//TRANSLIT")
  
  # Converter para minúsculas
  colnames(df) <- tolower(colnames(df))
  
  # Substituir espaços por underscores
  colnames(df) <- str_replace_all(colnames(df), " ", "_")
  
  # Remover caracteres especiais, mantendo apenas letras, números e underscores
  colnames(df) <- gsub("[^a-z0-9_]", "", colnames(df))
  
  # Substituir múltiplos underscores consecutivos por um único underscore
  colnames(df) <- gsub("_+", "_", colnames(df))
  
  # Remover underscores no início ou fim dos nomes de colunas
  colnames(df) <- gsub("^_|_$", "", colnames(df))
  
  return(df)
}

df = normalize_column_names(df)
df_bckp = df
df_bckp$mes = factor(df_bckp$mes, levels = c('Janeiro', 'Fevereiro', 'Março', 
                                             'Abril', 'Maio', 'Junho', 'Julho'))
df
```

# Preparando os dados para gerar os boxplots

```{r}
# Transformando para o formato longo
df$ID = 1:nrow(df)
dados_long = pivot_longer(df, cols = starts_with('nota_da_dor'),
                          names_to = "momentos", values_to = "medida_numerica")
dados_long$mes = factor(dados_long$mes, levels = c('Janeiro', 'Fevereiro', 'Março', 
                                                   'Abril', 'Maio', 'Junho', 'Julho'))
dados_long_bckp = dados_long
dados_long
```


```{r}
graficos_notas = ggplot() +
  geom_boxplot(data=dados_long, aes(x=as.factor(momentos), y=medida_numerica, color=as.factor(momentos)),
               alpha=0.5, fill = 'white', show.legend = F) +
  geom_point(data=dados_long, aes(x=as.factor(momentos), y=medida_numerica, color=as.factor(momentos)),
             alpha=0.5, size=2.5, show.legend = F) +
  geom_line(data=dados_long, aes(x=as.factor(momentos), y=medida_numerica, color='grey', group = ID), color='grey',
            alpha=0.1, show.legend = F) +
  labs(x=NULL, y='Notas da Dor (n)', title=NULL) +
  scale_x_discrete(labels=c('Avaliação','Reavaliação')) +
  theme(legend.position = "none") + theme_bw() +
  facet_grid(~mes)
graficos_notas
#ggsave("Graficos/Boxplot_pareado_por_mes.png", height=15, width=35, units="cm", dpi= 600)
############################################################################

coluna1 = 'reavaliacao_com_diminuicao_do_score_de_dor_em_ate_3_pontos'
grafi1 = df %>% 
  group_by(mes, !!sym(coluna1)) %>% 
  summarise(n = n()) %>% 
  mutate(frequencia = round(n/sum(n)*100, 2)) %>%
  ungroup() %>%
  filter(!!sym(coluna1) == TRUE) %>%
  mutate(coluna = coluna1)

coluna2 = 'reavaliacao_em_ate_1_hora'
grafi2 = df %>% 
  group_by(mes, !!sym(coluna2)) %>% 
  summarise(n = n()) %>% 
  mutate(frequencia = round(n/sum(n)*100, 2)) %>%
  ungroup() %>%
  filter(!!sym(coluna2) == TRUE) %>%
  mutate(coluna = coluna2)

combined_grafi = bind_rows(grafi1, grafi2)
combined_grafi$texto = paste0(round(combined_grafi$n, 0), ' (', round(combined_grafi$frequencia, 1), '%)')
combined_grafi$mes = factor(combined_grafi$mes, levels = c('Janeiro', 'Fevereiro', 'Março', 
                                                   'Abril', 'Maio', 'Junho', 'Julho'))

graficos_med = ggplot(combined_grafi, 
                      aes(x=as.factor(coluna), y=frequencia, label=frequencia, fill=as.factor(coluna))) +
  geom_col(color="black") +
  geom_text(aes(y=frequencia, label = texto, vjust=-0.5)) +
  theme_bw() + theme(legend.position = "bottom") + theme(
    axis.text.x = element_blank(), # Remove os textos do eixo x
    axis.ticks.x = element_blank()  # Remove os ticks do eixo x
  ) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(from = 0, to = 100, by = 20)) +
  scale_fill_manual(values = c('#00bbf9','#00f5d4'),
                    labels = c('Reavaliação com Diminuição do Score em até 3 pontos', 'Reavaliação em até 1H')) +
  labs(x=NULL, y="Frequency (%)", title =NULL, fill=NULL) +
  facet_grid(~mes) 
graficos_med
#ggsave("Graficos/Contagem_por_mes.png", height=15, width=35, units="cm", dpi= 600)

# Combinar os gráficos com um título geral
combined_plot <- graficos_notas / graficos_med + 
  plot_annotation(title = "Geral", 
                  theme = theme(plot.title = element_text(hjust = 0.5)))
print(combined_plot)
ggsave("Graficos/Geral.png", height=25, width=35, units="cm", dpi= 600)
```




```{r}

for (i in dados_long_bckp$setor %>% as.factor() %>% levels()){
  print(i)
  df = df_bckp %>% filter(setor == i)
  dados_long = dados_long_bckp %>% filter(setor == i)

  graficos_notas = ggplot() +
    geom_boxplot(data=dados_long, aes(x=as.factor(momentos), y=medida_numerica, color=as.factor(momentos)),
                 alpha=0.5, fill = 'white', show.legend = F) +
    geom_point(data=dados_long, aes(x=as.factor(momentos), y=medida_numerica, color=as.factor(momentos)),
               alpha=0.5, size=2.5, show.legend = F) +
    geom_line(data=dados_long, aes(x=as.factor(momentos), y=medida_numerica, color='grey', group = ID), color='grey',
              alpha=0.1, show.legend = F) +
    labs(x=NULL, y='Notas da Dor (n)', title=NULL) +
    scale_x_discrete(labels=c('Avaliação','Reavaliação')) +
    theme(legend.position = "none") + theme_bw() +
    facet_grid(~mes)
  #graficos_notas
  #ggsave("Graficos/Boxplot_pareado_por_mes.png", height=15, width=35, units="cm", dpi= 600)
  ############################################################################
  
  coluna1 = 'reavaliacao_com_diminuicao_do_score_de_dor_em_ate_3_pontos'
  grafi1 = df %>% 
    group_by(mes, !!sym(coluna1)) %>% 
    summarise(n = n()) %>% 
    mutate(frequencia = round(n/sum(n)*100, 2)) %>%
    ungroup() %>%
    filter(!!sym(coluna1) == TRUE) %>%
    mutate(coluna = coluna1)
  
  coluna2 = 'reavaliacao_em_ate_1_hora'
  grafi2 = df %>% 
    group_by(mes, !!sym(coluna2)) %>% 
    summarise(n = n()) %>% 
    mutate(frequencia = round(n/sum(n)*100, 2)) %>%
    ungroup() %>%
    filter(!!sym(coluna2) == TRUE) %>%
    mutate(coluna = coluna2)
  
  combined_grafi = bind_rows(grafi1, grafi2)
  combined_grafi$texto = paste0(round(combined_grafi$n, 0), ' (', round(combined_grafi$frequencia, 1), '%)')
  combined_grafi
  
  graficos_med = ggplot(combined_grafi, 
                        aes(x=as.factor(coluna), y=frequencia, label=frequencia, fill=as.factor(coluna))) +
    geom_col(color="black") +
    geom_text(aes(y=frequencia, label = texto, vjust=-0.5)) +
    theme_bw() + theme(legend.position = "bottom") + theme(
      axis.text.x = element_blank(), # Remove os textos do eixo x
      axis.ticks.x = element_blank()  # Remove os ticks do eixo x
    ) +
    scale_y_continuous(limits = c(0, 100), breaks=seq(from = 0, to = 100, by = 20)) +
    scale_fill_manual(values = c('#00bbf9','#00f5d4'),
                      labels = c('Reavaliação com Diminuição do Score em até 3 pontos', 'Reavaliação em até 1H')) +
    labs(x=NULL, y="Frequency (%)", title =NULL, fill=NULL) +
    facet_grid(~mes) 
  #graficos_med
  #ggsave("Graficos/Contagem_por_mes.png", height=15, width=35, units="cm", dpi= 600)
  
  # Combinar os gráficos com um título geral
  combined_plot <- graficos_notas / graficos_med + 
    plot_annotation(title = i, 
                    theme = theme(plot.title = element_text(hjust = 0.5)))
  ggsave(paste0("Graficos/",i,".png"), plot = combined_plot, height=25, width=35, units="cm", dpi= 600)
}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

